### PR TITLE
Fix/address monospace

### PR DESCRIPTION
**Pull request by jensendarren**

### CODE REVIEW

**Review by JatinBumbra — APPROVED** [review]

**Comment by JatinBumbra** [comment]
@jensendarren I've approved the PR but, just a personal opinion, that the earlier font looked better. I don't know how you feel about it?

**Comment by amherag** [comment]
I think the letters look too thin.

**Comment by jensendarren** [comment]
I think it's maybe a good idea to loop in Juan to help.

**Comment by JatinBumbra** [comment]
There is a new UI design now so closing the PR

**Pull request closed without merging**
